name: hiring_leaderboard
version: "1.0.0"
config-version: 2

profile: hiring_leaderboard

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  hiring_leaderboard:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
